SELECT * FROM [TABELA DE VENDEDORES]
SELECT * FROM [NOTAS FISCAIS]

--Juntando as duas tabelas (new school)
SELECT * FROM [TABELA DE VENDEDORES] V INNER JOIN [NOTAS FISCAIS]N
ON V.MATRICULA = N.MATRICULA

--Juntando as duas tabelas (old school)
SELECT * FROM [TABELA DE VENDEDORES], [NOTAS FISCAIS]
WHERE dbo.[TABELA DE VENDEDORES].MATRICULA = dbo.[NOTAS FISCAIS].MATRICULA

--Também é possível usar o nome da própria tabela
SELECT * FROM [TABELA DE VENDEDORES] INNER JOIN [NOTAS FISCAIS]
ON dbo.[TABELA DE VENDEDORES].MATRICULA = dbo.[NOTAS FISCAIS].MATRICULA

--Definindo o número de notas fiscais por vendedor
SELECT V.MATRICULA, V.NOME, COUNT(*) AS QTDNOTAS FROM [TABELA DE VENDEDORES] V INNER JOIN [NOTAS FISCAIS]N
ON V.MATRICULA = N.MATRICULA GROUP BY V.MATRICULA, V.NOME

--Definindo o número de notas fiscais por ano e vendedor
SELECT YEAR(N.DATA) AS ANO, V.MATRICULA, V.NOME, COUNT(*) AS QTDNOTAS FROM [TABELA DE VENDEDORES] V INNER JOIN [NOTAS FISCAIS] N
ON V.MATRICULA = N.MATRICULA GROUP BY YEAR(N.DATA), V.MATRICULA, V.NOME 

--Definindo o número de notas fiscais por ano e vendedor ordernados por ano
SELECT YEAR(N.DATA) AS ANO, V.MATRICULA, V.NOME, COUNT(*) AS QTDNOTAS FROM [TABELA DE VENDEDORES] V INNER JOIN [NOTAS FISCAIS] N
ON V.MATRICULA = N.MATRICULA GROUP BY YEAR(N.DATA), V.MATRICULA, V.NOME ORDER BY ANO 
