SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES, 
CASE WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
     WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
END AS STATUS_VENDA
FROM
(SELECT TC.NOME, TC.[VOLUME DE COMPRA],CQ.ANO_MES, CQ.QUANTIDADE_MES
FROM
(
SELECT N.CPF, SUBSTRING(CONVERT(VARCHAR, N.DATA,120),1,7) ANO_MES, SUM(I.QUANTIDADE) QUANTIDADE_MES FROM [NOTAS FISCAIS] N INNER JOIN [ITENS NOTAS FISCAIS] I
ON N.NUMERO = I.NUMERO
GROUP BY N.CPF, SUBSTRING(CONVERT(VARCHAR, N.DATA, 120), 1, 7)
) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF
) AUX1
ORDER BY AUX1.NOME, AUX1.ANO_MES


SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES, AUX1.[VOLUME DE COMPRA], ROUND((1-(AUX1.[VOLUME DE COMPRA]/AUX1.[QUANTIDADE_MES])) * 100,2)
FROM
(SELECT TC.NOME, TC.[VOLUME DE COMPRA],CQ.ANO_MES, CQ.QUANTIDADE_MES
FROM
(
SELECT N.CPF, SUBSTRING(CONVERT(VARCHAR, N.DATA,120),1,7) ANO_MES, SUM(I.QUANTIDADE) QUANTIDADE_MES FROM [NOTAS FISCAIS] N INNER JOIN [ITENS NOTAS FISCAIS] I
ON N.NUMERO = I.NUMERO
GROUP BY N.CPF, SUBSTRING(CONVERT(VARCHAR, N.DATA, 120), 1, 7)
) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF
) AUX1 
WHERE AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA]
ORDER BY AUX1.NOME, AUX1.ANO_MES

