SELECT AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + '%' AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR(NF.DATA)
HAVING YEAR(NF.DATA) = 2016) AUX1
INNER JOIN
(SELECT YEAR(NF.DATA) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS TOTAL FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF ON NF.NUMERO = INF.NUMERO
GROUP BY  YEAR(NF.DATA)
HAVING YEAR(NF.DATA) = 2016) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC
